### ISSUE TITLE
ansible_docker_extra_args is ignored by "Docker version check"

### ISSUE THREAD

**Issue by mit0223** [ansible-collections/community.docker#325] opened 2022-03-31 13:04 UTC
##### SUMMARY
Starting with version 2.3.1, ansible_docker_extra_args is ignored by "Docker version check".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugin/connection/docker

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/Users/mitsuru/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mitsuru/.pyenv/versions/3.9.5/envs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/mitsuru/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/mitsuru/.pyenv/versions/ansible/bin/ansible
  python version = 3.9.5 (default, Jun  7 2021, 21:55:20) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```paste below
Collection       Version
---------------- -------
community.docker 2.3.0  
```

##### CONFIGURATION
no specific configuration

##### OS / ENVIRONMENT
MacOS Monterey 12.2.1

##### STEPS TO REPRODUCE
the container 'iperf' should be running on the remote host 'test-server'.
```
ssh -N -L /var/tmp/test.sock:/var/run/docker.sock test-server &
ansible-playbook -i iperf, book.yml
```
book.yml:
```yaml
- hosts: all
  connection: docker
  vars:
    ansible_docker_extra_args: "-H unix:///var/tmp/test.sock"
  tasks:
  - debug: var=ansible_docker_extra_args
```

##### EXPECTED RESULTS
no error if version 2.2.1 is installed.
```
(ansible) mit0223:ansible mitsuru$ ansible-playbook -i iperf, book.yml

PLAY [all] **********************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************
[WARNING]: Platform linux on host iperf is using the discovered Python interpreter at /usr/bin/python3.8, but future installation of another
Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.12/reference_appendices/interpreter_discovery.html for more information.
ok: [iperf]

TASK [debug] ********************************************************************************************************************************
ok: [iperf] => {
    "ansible_docker_extra_args": "-H unix:///var/tmp/test.sock"
}

PLAY RECAP **********************************************************************************************************************************
iperf                      : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS
error occur: "Docker version check (['/usr/local/bin/docker', 'version', '--format', \"'{{.Server.Version}}'\"]) failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```paste below
(ansible) mit0223:ansible mitsuru$ ansible-playbook -i iperf, book.yml

PLAY [all] **********************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************
fatal: [iperf]: FAILED! => {"msg": "Docker version check (['/usr/local/bin/docker', 'version', '--format', \"'{{.Server.Version}}'\"]) failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n"}

PLAY RECAP **********************************************************************************************************************************
iperf                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by felixfontein** [comment] 2022-03-31 17:13
This is probably caused by #297. I'll take a look later.

**Comment by felixfontein** [comment] 2022-03-31 17:16
This is very likely caused by the version check happening in `__init__()`. I guess it should move to `_connect()`. @bcoca is `_connect()` always called before any operation (like put, fetch, exec_comand)?

**Comment by felixfontein** [comment] 2022-03-31 18:46
I created a potential fix in #326. @mit0223 can you test whether that fixes your problem?

**Comment by mit0223** [comment] 2022-03-31 22:33
@felixfontein I tried replacing "plugins/connection/docker.py", but it looks like the behavior hasn't changed.

**Comment by bcoca** [comment] 2022-04-01 13:20
@felixfontein we don't need to move the version assignment from init, that won't help (unless you are changing the docker installed while running .. which DON'T).

**Comment by bcoca** [comment] 2022-04-01 13:22
didn't realize  #297 was merged, i had fix for this issue in my branch, will push to new PR

**Comment by bcoca** [comment] 2022-04-01 13:41
```
diff --git a/plugins/connection/docker.py b/plugins/connection/docker.py
index f039b99..22eaf02 100644
--- a/plugins/connection/docker.py
+++ b/plugins/connection/docker.py
@@ -80,6 +80,7 @@ DOCUMENTATION = '''
 import fcntl
 import os
 import os.path
+import shlex
 import subprocess
 import re

@@ -227,9 +228,9 @@ class Connection(ConnectionBase):
         # TODO: this is mostly for backwards compatibility, play_context is used as fallback for older versions
         # docker arguments
         del self._docker_args[:]
-        extra_args = self.get_option('docker_extra_args') or self._play_context.docker_extra_args
+        extra_args = self.get_option('docker_extra_args') or getattr(self._play_context, 'docker_extra_args', '')
         if extra_args:
-            self._docker_args += extra_args.split(' ')
+            self._docker_args = shlex.split(extra_args)

         self.remote_user = self.get_option('remote_user')
         if self.remote_user is None and self._play_context.remote_user is not None:
```

**Comment by bcoca** [comment] 2022-04-01 13:45
ok, the issue is that everything uses exec_command or _build_exec_command, so those that try to use the docker command should also add the self._docker_args

**Comment by bcoca** [comment] 2022-04-01 13:55
nvmd, not only thing needed, i see why you moved the version .. probably we should just create accessors.

**Closed** 2022-04-25 18:35 UTC
Labels: bug, docker-plain
