### ISSUE TITLE
Cant resolve module/action 'community.docker.docker_host_info'

### ISSUE THREAD

**Issue by mjtrangoni** [ansible-collections/community.docker#629] opened 2023-05-19 13:21 UTC
##### SUMMARY
Building my custom EE image based on latest https://github.com/ansible/awx-ee pipeline I get the following issue with **community.docker** `3.4.5`. 

```bash
ERROR! couldn't resolve module/action 'community.docker.docker_host_info'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/playbook.yml': line 170, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - name: docker info test
      ^ here
```

where  the failing part of `playbook.yml` is,

```yaml
- name: docker info test
  community.docker.docker_host_info:
  register: result
```

**NOTE**: Current workaround is downgrading to `3.4.3` where it works as it should.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.docker.docker_host_info, but we saw the same behaviour with different modules in this collection.

##### ANSIBLE VERSION

```bash
$ ansible --version
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Dec  8 2022, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```bash
$ ansible-galaxy collection list community.docker

# /usr/share/ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.5
```

##### CONFIGURATION

```bash
ansible-config dump --only-changed
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

**awx-ee base image**: `quay.io/rockylinux/rockylinux:9`

##### STEPS TO REPRODUCE

```yaml
- name: docker info test
  community.docker.docker_host_info:
  register: result
```

##### EXPECTED RESULTS

no error

##### ACTUAL RESULTS

We are running AWX on k8s, so no extra logs found here.

```bash
ERROR! couldn't resolve module/action 'community.docker.docker_host_info'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/playbook.yml': line 170, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - name: docker info test
      ^ here
```

**Comment by felixfontein** [comment] 2023-05-19 15:40
This error message usually indicates that you do not have community.docker installed. Did you run `ansible-galaxy collection list community.docker` inside the EE (where you apparently also run the playbook), or did you run it somewhere else?

Maybe try adding a task
```yaml
- command: ansible-galaxy collection list community.docker
  delegate_to: localhost
```
in a playbook to see what happens.

**Comment by mjtrangoni** [comment] 2023-05-19 21:14
@felixfontein I've run ansible-galaxy inside the container. Modifying the version in the ansible-builder config file from 3.4.5 to 3.4.3 just make it running again.

**Comment by felixfontein** [comment] 2023-05-20 07:34
I tried building an EE with community.docker 3.4.5 based on quay.io/rockylinux/rockylinux:9 with similar settings as yours: https://gist.github.com/felixfontein/a121653ec0d38ef50c58487d1ef1df79

If I run `run.sh` it works fine, or well:
```
TASK [docker info test] ********************************************************
task path: /path/to/test.yml:5
fatal: [localhost]: FAILED! => {"can_talk_to_docker": false, "changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"}
```
which is to be expected since Docker daemon isn't available inside the EE container.

So if there is a problem, it seems to be more with your specific setup, and not with community.docker 3.4.5 in general.

**Comment by felixfontein** [comment] 2023-05-26 19:40
@mjtrangoni do you have more precise steps to reproduce the problem? As mentioned above, community.docker 3.4.5 seems to work in EEs in general.

**Comment by felixfontein** [comment] 2023-06-27 19:41
Closing since there was no more information.

**Closed by felixfontein** 2023-06-27 19:41 UTC
